##
# Ansible playbook for setting up a DIRECT development server on EC2 Ubuntu 12.04 LTS 64bit medium instance.
#

---
## Global setup
- hosts: all
  tasks:
    - include: global_setup.yml

- hosts: all
  # replaced with group_vars and hosts_vars files
  #vars_files:
  #  - settings/direct_server.yml
  #  - settings/fixed.yml
  tasks:
    - include: direct_server.yml

## Global cleanup
- hosts: all
  tasks:
    - include: global_cleanup.yml
